#cloud-config

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - whois
package_update: true

# create the docker group
groups:
  - docker

# users
users:
  - name: htkoca
    groups: 
      - sudo
      - docker
    sudo: 
      - 'ALL=(ALL) NOPASSWD:ALL'
    passwd: <hash via 'mkpasswd --method=SHA-512 --rounds=4096'>
    ssh_authorized_keys:
      - <ssh pub key 1>

# Install env
runcmd:
  - (cd ~ && git clone git@github.com:htkoca/utils-deployment.git)
  - (cd ~/utils-deployment/scripts/ && ./install.sh)
  - (cd ~/utils-deployment/scripts/ && ./install-post.sh)
  - rm -rf ~/utils-deployment
  - cat /etc/passwd > ~/test.txt
