#cloud-config

# create the docker group
groups:
  - docker

# users
users:
  - name: htkoca
    groups: 
      - sudo
      - docker
    sudo: 
      - 'ALL=(ALL) PASSWD:ALL'
    shell: '/bin/bash'
    ssh_authorized_keys:
      - <ssh pub key>

# Install env
runcmd:
  - usermod --password $(openssl passwd -1 somepassword) htkoca
  - sed -i -r -e '/^#?Port/s/^.*$/Port 8022/' /etc/ssh/sshd_config
  - sed -i -r -e '/^#?ListenAddress 0.0.0.0/s/^.*$/ListenAddress 0.0.0.0/' /etc/ssh/sshd_config
  - systemctl restart sshd